# Generated by Django 6.0.2 on 2026-03-19 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_telemetria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicaoVeiculoTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arquivoid', models.CharField(db_index=True, max_length=256)),
                ('medicaoid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_telemetria.medicao')),
                ('veiculoid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_telemetria.veiculo')),
            ],
            options={
                'verbose_name': 'Medição Temporária',
                'verbose_name_plural': 'Medições Temporárias',
            },
        ),
    ]
