# Generated by Django 6.0.2 on 2026-02-19 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_telemetria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leitura',
            options={'ordering': ['-data_hora'], 'verbose_name': 'Leitura', 'verbose_name_plural': 'Leituras'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['id'], 'verbose_name': 'Sensor', 'verbose_name_plural': 'Sensores'},
        ),
        migrations.AlterModelOptions(
            name='setor',
            options={'ordering': ['nome'], 'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
        migrations.AlterField(
            model_name='leitura',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora'),
        ),
        migrations.AlterField(
            model_name='leitura',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='api_telemetria.sensor', verbose_name='Sensor'),
        ),
        migrations.AlterField(
            model_name='leitura',
            name='valor',
            field=models.FloatField(verbose_name='Valor da Leitura'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='api_telemetria.setor', verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='status',
            field=models.CharField(max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='tipo',
            field=models.CharField(max_length=100, verbose_name='Tipo de Sensor'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='localizacao',
            field=models.CharField(max_length=200, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Setor'),
        ),
        migrations.AddIndex(
            model_name='leitura',
            index=models.Index(fields=['-data_hora'], name='api_telemet_data_ho_a5a983_idx'),
        ),
        migrations.AddIndex(
            model_name='leitura',
            index=models.Index(fields=['sensor', '-data_hora'], name='api_telemet_sensor__35a260_idx'),
        ),
    ]
