# Generated by Django 6.0.2 on 2026-04-16 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_telemetria', '0002_medicaoveiculotemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicaoVeiculoIoT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField(help_text='Temperatura do motor em Celsius (-50°C a 250°C)')),
                ('vibracao', models.FloatField(help_text='Vibração em mm/s (0 a 100)')),
                ('rpm', models.IntegerField(help_text='Rotações por minuto (0 a 10000)')),
                ('timestamp_coleta', models.DateTimeField(db_index=True, help_text='Timestamp de coleta no ESP32')),
                ('timestamp_recebimento', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Quando o backend recebeu a medição')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes_iot', to='api_telemetria.veiculo')),
            ],
            options={
                'verbose_name': 'Medição IoT',
                'verbose_name_plural': 'Medições IoT',
                'ordering': ['-timestamp_recebimento'],
                'indexes': [models.Index(fields=['veiculo', '-timestamp_recebimento'], name='api_telemet_veiculo_8f526c_idx'), models.Index(fields=['timestamp_coleta'], name='api_telemet_timesta_1e97cf_idx')],
                'unique_together': {('veiculo', 'timestamp_coleta')},
            },
        ),
    ]
