# Generated by Django 6.0.2 on 2026-05-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_telemetria', '0003_medicaoveiculoiot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaoveiculo',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
    ]
