# Generated by Django 6.0.2 on 2026-05-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_telemetria', '0004_alter_medicaoveiculo_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaoveiculo',
            name='data',
            field=models.DateTimeField(verbose_name='Data e Hora'),
        ),
    ]
