# Generated by Django 6.0.2 on 2026-02-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('area', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cultura', models.CharField(max_length=100)),
            ],
        ),
    ]
